export const siteConfig = {
  name: "TRUPTHI",
  teluguName: "తృప్తి",
  fullName: "TRUPTHI (తృప్తి) – Pure Organic Food & Traditional Telugu Dining",
  tagline: "Pure Organic Food. Authentic Telugu Taste.",
  teluguTagline: "ప్రకృతి నుంచి... పళ్లెం వరకు",
  teluguSubtitle: "గోవు ఆధారిత ప్రకృతి ఉత్పత్తులు మరియు ఆహారం",
  description:
    "Experience authentic Telugu vegetarian cuisine at TRUPTHI. Pure desi cow ghee, farm-fresh organic ingredients, stone-ground spices, and traditional recipes slow-cooked in clay pots.",
  url: "https://trupthi-restaurant.com",
  ogImage: "/images/hero-bhojanam.jpg",
  logo: "/logo/trupthi-logo-transparent.png",
  contact: {
    phone: "+91 91234 56789",
    rawPhone: "+919123456789",
    whatsappPhone: "919123456789",
    email: "namaste@trupthi-restaurant.com",
    address: "Plot No. 18, VIP Road, Near Siripuram Circle, Waltair Uplands, Visakhapatnam (Vizag), Andhra Pradesh - 530003",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    postalCode: "530003",
    country: "IN",
    geo: {
      latitude: 17.7231,
      longitude: 83.3150,
    },
  },
  coordinates: {
    latitude: 17.7231,
    longitude: 83.3150,
  },

  openingHours: {
    weekdays: "07:00 AM – 10:30 PM",
    weekends: "06:30 AM – 11:00 PM",
    feastLunch: "12:00 PM – 03:30 PM",
    feastDinner: "07:00 PM – 10:30 PM",
  },
  socials: {
    instagram: "https://instagram.com/trupthi.bhojanam",
    facebook: "https://facebook.com/trupthi.bhojanashala",
    youtube: "https://youtube.com/@trupthi-telugu-kitchen",
  },
  keywords: [
    "TRUPTHI Restaurant Vizag",
    "తృప్తి రెస్టారెంట్ విశాఖపట్నం",
    "Andhra Bhojanam Vizag",
    "Best Vegetarian Restaurant in Vizag",
    "Pure Desi Cow Ghee Telugu Vegetarian Restaurant Visakhapatnam",
    "Traditional Telugu Cuisine Visakhapatnam",
    "Banana Leaf Meals Vizag",
    "MLA Pesarattu Vizag",
    "Godavari Pootharekulu Sweets Vizag",
    "Gutti Vankaya Bhojanam Vizag",
    "Clay Pot Cooking Visakhapatnam",
    "Pure Vegetarian Restaurant Siripuram Vizag",
    "Satvik Telugu Food Vizag",
    "Authentic Andhra Thali Visakhapatnam",
    "Waltair Uplands Veg Restaurants",
  ],
};
