export const siteConfig = {
  name: "TRUPTHI",
  teluguName: "తృప్తి",
  fullName: "TRUPTHI (తృప్తి) – Pure Organic Food & Traditional Telugu Dining",
  tagline: "Pure Organic Food. Authentic Telugu Taste.",
  teluguTagline: "ప్రకృతి నుంచి... పళ్లెం వరకు",
  teluguSubtitle: "గోవు ఆధారిత ప్రకృతి ఉత్పత్తులు మరియు ఆహారం",
  description:
    "Experience authentic Telugu vegetarian cuisine at TRUPTHI. Pure desi cow ghee, farm-fresh organic ingredients, stone-ground spices, and traditional recipes slow-cooked in clay pots.",
  url: "https://trupthi-restaurant.com",
  ogImage: "https://res.cloudinary.com/djaaoxrv9/image/upload/v1789108766/hero-bhojanam_rzk7lq.jpg",
  logo: "https://res.cloudinary.com/djaaoxrv9/image/upload/v1789108749/trupthi-logo-transparent_po0w30.png",
  contact: {
    phone: "+91 94900 62627",
    rawPhone: "+919490062627",
    whatsappPhone: "919490062627",
    address: "Q9H3+963 Petrol Bunk, Yendada, Endada, Visakhapatnam, Andhra Pradesh - 530045",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    postalCode: "530045",
    country: "IN",
    geo: {
      latitude: 17.7761,
      longitude: 83.3547,
    },
  },
  coordinates: {
    latitude: 17.7761,
    longitude: 83.3547,
  },

  openingHours: {
    weekdays: "08:00 AM – 11:00 PM",
    weekends: "08:00 AM – 11:00 PM",
    tiffin: "08:00 AM – 11:00 AM",
    feastLunch: "12:00 PM – 03:30 PM",
    feastDinner: "07:00 PM – 11:00 PM",
  },
  socials: {
    instagram: "https://instagram.com/trupthi.bhojanam",
    facebook: "https://facebook.com/trupthi.bhojanashala",
    youtube: "https://youtube.com/@trupthi-telugu-kitchen",
  },
  keywords: [
    "TRUPTHI Restaurant Vizag",
    "తృప్తి రెస్టారెంట్ విశాఖపట్నం",
    "Andhra Bhojanam Vizag",
    "Best Vegetarian Restaurant in Vizag",
    "Pure Desi Cow Ghee Telugu Vegetarian Restaurant Visakhapatnam",
    "Traditional Telugu Cuisine Visakhapatnam",
    "Banana Leaf Meals Vizag",
    "MLA Pesarattu Vizag",
    "Millet Idli Vizag",
    "Clay Pot Cooking Visakhapatnam",
    "Pure Vegetarian Restaurant Yendada Vizag",
    "Satvik Telugu Food Vizag",
    "Authentic Andhra Tiffin Visakhapatnam",
    "Yendada Endada Veg Restaurants",
  ],
};
